name: Upload to S3

on:
  push:
    branches:
      - main
      
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
        unzip -q /tmp/awscliv2.zip -d /tmp
        rm /tmp/awscliv2.zip
        sudo /tmp/aws/install --update
        rm -rf /tmp/aws/

    - name: Sync files to S3
      run: |
        bucket_name=$(aws s3 ls | cut -d ' ' -f 3 | grep code-build-source | xargs)
        git archive --format zip -o source.zip HEAD
        aws s3 cp source.zip s3://$bucket_name/source.zip --exclude ".git/*"
      env:
        AWS_DEFAULT_REGION: us-west-2
